### ISSUE TITLE
Bug when importing .css.ts file

### ISSUE THREAD

**Issue by phil-lgr** [KyleAMathews/gatsby-plugin-vanilla-extract#9]
"gatsby": "^2.32.13",
"@vanilla-extract/css": "^1.0.0",
"@vanilla-extract/babel-plugin": "^1.0.0",
"@vanilla-extract/css-utils": "^0.1.1",
"@vanilla-extract/webpack-plugin": "^1.0.1",
"gatsby-plugin-vanilla-extract": "^1.0.5",

I'm creating a theme in my gatsby app

```ts
import { defaultButtons, themeVars } from '@newrade/core-react-ui';
import { createTheme } from '@vanilla-extract/css';

export const themeClassName = createTheme(themeVars, {
  buttons: {
    ...defaultButtons,
    medium: {
      ...defaultButtons.medium,
      padding: {
        default: '40px',
      },
    },
  },
});
```

and then importing it

```ts
import { themeClassName } from '../design-system/theme.css';
```

Somehow I'm getting this error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

(Emitted value instead of an instance of Error) ReferenceError: window is not defined

File: src/design-system/theme.css.ts

failed Re-building development bundle - 2.975s

```

```
./src/design-system/theme.css.ts
Module build failed (from /Users/phil/Code/newrade/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: window is not defined
    at /Users/phil/Code/newrade/node_modules/webpack/lib/NormalModule.js:313:13
    at /Users/phil/Code/newrade/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/phil/Code/newrade/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/phil/Code/newrade/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/phil/Code/newrade/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.dev.js:58:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I get this while running `gatsby develop`

What is weird is I have a default theme in another package and I can import that one fine, but locally created theme fails

**Comment by KyleAMathews** [comment]
Could you create and share a reproduction repo?

**Comment by phil-lgr** [comment]
Is there a reason why this plugin should run on `develop` stage?

```
  if (stage === "develop" || stage === "build-javascript") {
```

I'm importing a .css.ts file in gatsby-browser and it seems to cause an error

**Comment by KyleAMathews** [comment]
`develop` is the stage for the develop server. This wouldn't work while developing otherwise.

**Comment by phil-lgr** [comment]
Ah, yes, thanks for the clarification

I've upgraded to webpack ^5.24.2 and gatsby ^3.5.1

I'm getting the same error

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Module build failed (from ../../node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:23
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:15:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at _next0 (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:11:1)
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:24:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)

File: src/design-system/theme.css.ts

failed Building development bundle - 29.616s
ERROR in ./src/design-system/theme.css.ts
Module build failed (from 
../../node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
ModuleBuildError: Module build failed (from ../../node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:23
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:15:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at _next0 (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:11:1)
    at eval (eval at create (/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10),
<anonymous>:24:1)
    at fn (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:464:9)
    at processResult (/Users/phil/Code/newrade-core/node_modules/webpack/lib/NormalModule.js:701:19)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/NormalModule.js:807:5
    at /Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:195:20
    at context.callback (/Users/phil/Code/newrade-core/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/phil/Code/newrade-core/node_modules/gatsby/node_modules/mini-css-extract-plugin/dist/loader.js:311:14
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:548:11
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1118:17
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compiler.js:1114:33
    at finalCallback (/Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2249:11)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2540:11
    at Hook.eval [as callAsync] (eval at create
(/Users/phil/Code/newrade-core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/phil/Code/newrade-core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/phil/Code/newrade-core/node_modules/webpack/lib/Compilation.js:2533:38
 @ ./src/templates/src-page.template.tsx 8:0-36
 @ ./src/pages/404.tsx 9:0-65 49:42-57
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 17:41-19:3
 @ ./.cache/app.js 14:0-52 27:87-31:1 30:29-42 33:29-42 27:0-31:2
```

```ts
import {
  buttonsVars,
  colorVars,
  defaultCSSButtons,
  defaultCSSColors,
  defaultCSSSizing,
  sizingVars,
} from '@newrade/core-react-ui';
import { createGlobalTheme } from '@vanilla-extract/css';

// @ts-expect-error
createGlobalTheme(':root', sizingVars, defaultCSSSizing);
// @ts-expect-error
createGlobalTheme(':root', colorVars, defaultCSSColors);
// @ts-expect-error
createGlobalTheme(':root', buttonsVars, defaultCSSButtons);
```

When I save a file in my ui package it does the same error and then... works

**Comment by KyleAMathews** [comment]
It's hard to know why your code isn't working. If you can create a reproduction, I can look at debugging this https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

**Comment by phil-lgr** [comment]
It's hard because this is part of a 20 packages monorepo

It looks like it is crashing in the loader

![image](https://user-images.githubusercontent.com/9644867/125121066-5ee04c80-e0c1-11eb-88a0-75a4817f8a61.png)

Doesn't give much details... there is prob something wrong with my .css.ts files

I'll keep debugging and will report back

Enabling the DEBUG=vanilla-extract:loader* gives no insight either

![image](https://user-images.githubusercontent.com/9644867/125121347-cb5b4b80-e0c1-11eb-9708-e0400b866d39.png)

**Comment by phil-lgr** [comment]
Culprit was a function in a css.ts that should be outside (in a regular .ts file)

Closing as it's not related to this plugin
